# Generated by Django 5.2.5 on 2025-08-14 09:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupBooking',
            fields=[
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('pickup_location', models.CharField(max_length=255)),
                ('time_slot', models.DateTimeField()),
                ('waste_type', models.CharField(max_length=100)),
                ('approximate_weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('special_instructions', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('my_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='myapp.myuser')),
            ],
        ),
    ]
