# Generated by Django 5.2.5 on 2025-08-16 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_pickupbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickupbooking',
            name='pickup_location',
        ),
        migrations.AddField(
            model_name='pickupbooking',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='pickupbooking',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
