# Generated by Django 5.2.5 on 2025-08-16 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_pickupbooking_pickup_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='task',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mytask', to='myapp.pickupbooking'),
        ),
    ]
