# Generated by Django 5.2.5 on 2025-08-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_volunteerprofile_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickupbooking',
            name='status',
            field=models.CharField(choices=[('unassigned', 'Unassigned'), ('active', 'Active'), ('completed', 'Completed')], default='unassigned', max_length=20),
        ),
    ]
