# Generated by Django 5.2.5 on 2025-08-16 19:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_volunteerprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerprofile',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='contact_no',
            field=models.CharField(blank=True, help_text='Include country code. Example: +919876543210', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (10-15 digits).', regex='^\\+?\\d{10,15}$')]),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='id_number',
            field=models.CharField(blank=True, help_text='Aadhaar or PAN number', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='id_proof',
            field=models.ImageField(blank=True, null=True, upload_to='smartdustbin/'),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='smartdustbin/'),
        ),
    ]
