# Generated by Django 5.2.5 on 2025-08-17 04:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_volunteerprofile_address_volunteerprofile_contact_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='contact_no',
            field=models.CharField(blank=True, help_text='Include country code. Example: +919876543210', max_length=15, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (10-15 digits).', regex='^\\+?\\d{10,15}$')]),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='smartdustbin/'),
        ),
    ]
